services:
  jodos_db:
    image: postgres:15
    container_name: jodos_db
    env_file:
        - .env
    ports:
      - "${DB_PORT}:5432"
    volumes:
      - jodo-data:/var/lib/postgresql/data

volumes:
  jodo-data:
    name: jodo-data
